### ISSUE TITLE
Adding a way to suggest new content for a week's issue

### ISSUE THREAD

**Issue by josephmbustamante** [albizures/ThisWeekInGodot#6]
Hey there!

First, I want to say a huge thank you for creating this site and for maintaining it - it's really cool to have a Godot newsletter and to see all the creations everyone makes.

~~I wanted to ask - would it be possible to add a suggestion feature to the site? Maybe something like a contact form or link upload form that users could just paste a link towards a Godot tutorial or devlog, for example? That might be easier rather than emailing you, and might make the work you need to compile a new list every week lower. I'm not sure what your current workflow is, so maybe it wouldn't be helpful, but just wanted to see if you'd consider it.~~

Edit: I just realized this feature does exist, but only at the bottom of individual issues. Would it be possible to move this to the homepage?

Also, one other suggestion - if you made a Ko-fi or Buy Me a Coffee page (or a similar donation service) and had it linked here on GitHub and on the site itself, I (and others I'm sure) would definitely make use of it. This is a really cool service you're doing for the Godot community!

**Comment by albizures** [comment]
Thanks @josephmbustamante for your words and suggestions.

I will definitely add the suggestions form in the homepage and I will look into the donations part too 🙂
